### ISSUE TITLE
Add ability to locate substrings containing newlines

### ISSUE THREAD

**Issue by flintsteel7** [westonlit/sublocator#1]
I love this library, thanks for the great work.

There's a feature I'd like to see added, namely the ability to locate substrings which contain newline characters

Currently, when I do something like:
```elixir
Sublocator.locate("look for newlines \n in this string", "newlines \n in this")
```
I get:
```elixir
{:ok, []}
```
Which tells me Sublocator has not found a match for `"newlines \n in this"`

I believe you could allow for newlines within the pattern by following this approach:
- split the string on the pattern
- split the first portion of the split string on newlines
- line number would be the length of the resulting list (maybe +1 ?)
- column number would be the number of characters in the last member of the list

You could account for multiple matches by looking at the length of the list resulting from the first operation, and deal with them accordingly. Of course, line numbers after the first match would become a little more tricky to calculate, but nothing a little arithmetic couldn't handle.

It might be easiest to keep the existing line streaming code, and only use this new method if the input pattern contains newline characters.

I'd submit a pull request myself, but something tells me you might like to tackle this one ;-)

**Comment by wlittrell** [comment]
support added in v0.2.0
